config/routes.rb
RailsApp::Application.routes.draw do
  get "entries/index"

  root :to => 'entries#index'
  resources :entries
end

app/models/entry.rb
# vim:fileencoding=UTF-8
class Entry < ActiveRecord::Base
  attr_accessible :body
  attr_accessor :more

  paginates_per 30
  max_paginates_per 100

  scope :newly, order('created_at DESC')

  validates :body, :presence => {:message => "本文が入力されていません"}

  def subject
    body ? body.split("\n").first : "-"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
# vim:fileencoding=UTF-8
class EntriesController < ApplicationController
  def index
    @entry = Entry.new
    @entries = Entry.page(params[:page]).per(params[:per]).newly
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def create
    @entry = Entry.new
    @entry.body = params[:entry][:body]
    if @entry.save then
      flash[:notice] = '投稿しました'
      redirect_to entries_path
    else
      @entries = Entry.newly.limit(10)
      render :index
    end
  end

  def update
    @entry = Entry.find(params[:id])
    if params[:entry][:more] then
      @entry.body = [@entry.body, params[:entry][:more]].join("\n")
    else
      @entry.body = params[:entry][:body]
    end
    if @entry.save then
      flash[:notice] = params[:entry][:more] ? '追記しました' : '更新しました'
      redirect_to entry_path(@entry)
    else
      render :edit
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    if @entry.destroy then
      flash[:notice] = '削除しました'
    else
      flash[:level]  = 'error'
      flash[:notice] = '削除に失敗しました'
    end
    redirect_to entries_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def recent_entries(limit=30)
    Entry.newly.limit(limit)
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
  def textile(text)
    RedCloth.new(sanitize(text), [:filter_html, :filter_styles, :filter_classes, :filter_ids]).to_html
  end
end

app/views/entries/_entry.html.erb
<div class="entry">
  <h2 class="entry-subject"><%= link_to '・', entry_path(entry) %><%= entry.subject %><span class="entry-date"><%= entry.created_at.to_date %></span></h2>
  <div class="entry-body<%= is_open ? '' : ' entry-body-close' %>">
    <%= raw textile entry.body %>
    <p class="right">
    <%= link_to '編集', edit_entry_path(entry), :class => "btn btn-warning btn-mini" %>
    <%= link_to '削除', entry_path(entry), :data => {:confirm => '本当に削除してもよろしいですか？'}, :method => 'delete', :class => "btn btn-inverse btn-mini" %>
    </p>
    <div class="entry-body-footer">
      <div class="well">
        <%= form_for(entry, {:method => 'put'}) do |f| %>
          <%= f.text_area :more %>
          <%= f.submit "追記する", :class => 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
  <hr />
</div>

app/views/entries/edit.html.erb
<%= render :partial => 'layouts/errors', :locals => {:object => @entry} %>
<div class="hero-unit">
  <%= form_for(@entry) do |f| %>
    <p>
    記事を更新する
    </p>
    <div>
      <%= link_to 'textile記法', 'http://redcloth.org/textile/', :target => '_blank', :class => 'icon-question-sign' %>
      <%= f.text_area :body %>
    </div>
    <div>
      <%= f.submit "更新する", :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/entries/index.html.erb
<div>
  <%= form_for(@entry) do |f| %>
    <div class="tips">
      <%= link_to 'textile記法(Redmine Help)', 'http://redmine.jp/tech_note/textile/', :target => '_blank' %>
    </div>
    <div>
      <%= f.text_area :body %>
    </div>
    <div>
      <%= f.submit "投稿する" %>
    </div>
  <% end %>
</div>
<div class="entries">
  <%- for entry in @entries -%>
  <div class="entry">
    <h2 class="entry-subject"><%= entry.subject %></h2>
    <div class="entry-body">
      <%= raw textile entry.body %>
    </div>
  </div>
  <%- end -%>
</div>

app/views/entries/show.html.erb
<%= render :partial => 'entries/entry', :locals => {:entry=> @entry, :is_open => true} %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error alert-block">
    <a class="close" data-dismiss="alert" href="#">&times;</a>
    <h4 class="alert-heading"><i class="icon-ban-circle"></i>エラーが発生しました</h4>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<h4>新着記事一覧</h4>
<ul class="nav nav-list">      
  <%- recent_entries.inject(nil) do |current_date, entry| -%>
    <%- if current_date != entry.created_at.to_date -%>
    <li class="nav-header"><%= entry.created_at.to_date.to_s %></li>
  <% end %>
  <li><%= link_to truncate(entry.body, :length => 10), entry_path(entry) %></li>
  <%- entry.created_at.to_date -%>
  <%- end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BlogWiki" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <h1><a class="brand" href="/">BlogWiki</a></h1>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "トップページ", "/" %></li>
              <li><%= link_to "RedCloth(記法)", "http://redcloth.org/textile/" %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
             <%- if flash[:notice] -%>
             <div class="alert alert-<%= flash[:level].blank? ? 'success' : flash[:level] %>">
               <%= h flash[:notice] %>
             </div>
             <%- end -%>
             <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <%= render :partial => 'layouts/sidebar' %>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
      <p>Generated by <%= link_to 'BlogWiki', 'https://github.com/chocomint/blogwiki' %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>